bindShared should be singleton in
With laravel framework 5.2.10

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Fatal error: Call to undefined method Illuminate\Foundation\Application::bindShared()

bindShared is removed and singleton should be used instead https://github.com/laravel/framework/commit/4b57379796a6c548d331bc1e622d51f3eb5904ca

Starting from 5.1
https://github.com/laravel/framework/pull/9009